# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLEARExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CLEARExam
    pod 'Alamofire', '~> 4.7.2'
    pod 'SwiftyJSON', '~> 4.1.0'
  
  target 'CLEARExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
